jobs:
  configlet:
    uses: exercism/github-actions/.github/workflows/configlet.yml@main
    with:
      fmt: true
name: Configlet
on:
  repository_dispatch:
    types: trigger-ga___configlet.yml
permissions:
  contents: read
