jobs:
  build:
    name: Check if tests compile cleanly with starter sources
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Set up JDK 1.17
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Check if tests compile cleanly with starter sources
      run: ./gradlew compileStarterTestJava --continue
      working-directory: exercises
  lint:
    name: Lint Java files using Checkstyle
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Set up JDK 1.17
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Run checkstyle
      run: ./gradlew check --exclude-task test --continue
      working-directory: exercises
  test:
    name: Test all exercises using java-test-runner
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Test all exercises using java-test-runner
      run: bin/test-with-test-runner
    - continue-on-error: true
      if: failure()
      name: Archive test results
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
        name: test-results
        path: exercises/**/build/results.json
name: Java
on:
  repository_dispatch:
    types: trigger-ga___java.yml
