jobs:
  lint:
    name: Lint Markdown files
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Lint markdown
      uses: DavidAnson/markdownlint-cli2-action@510b996878fc0d1a46c8a04ec86b06dbfba09de7
name: Markdown
on:
  repository_dispatch:
    types: trigger-ga___markdown.yml
permissions:
  contents: read
