jobs:
  pause:
    uses: exercism/github-actions/.github/workflows/check-no-important-files-changed.yml@main
    with:
      ref: ${{ github.head_ref }}
      repository: ${{ github.event.pull_request.head.repo.owner.login }}/${{ github.event.pull_request.head.repo.name
        }}
name: No important files changed
on:
  repository_dispatch:
    types: trigger-ga___no-important-files-changed.yml
permissions:
  pull-requests: write
